version: "3.4"
services:
  php:
    build:
      context: .
      args:
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
      dockerfile: ./docker/Dockerfile
    container_name: docker-php
    restart: always
    networks:
      localca:
        ipv4_address: ${SUBNET}.2
    volumes:
      - "./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./docker/data/logs/php/:/var/log/php-fpm/"
      - "./docker/data/lock/:/lock/"
      - "./:/var/www/html"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - XDEBUG_SESSION=${XDEBUG_SESSION}
    extra_hosts:
      - "${NGINX_HOST}:${SUBNET}.4"
    depends_on:
      - mysql
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: docker-${MYSQL_HOST}
    networks:
      localca:
        ipv4_address: ${SUBNET}.3
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./docker/data/db/mysql:/var/lib/mysql"
#      - "./docker/etc/mysql:/docker-entrypoint-initdb.d"
  nginx:
    image: nginx:alpine
    container_name: docker-nginx-server
    volumes:
      - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./:/var/www/html"
      - "./docker/data/logs/nginx/access.log:/var/logs/nginx/access.log"
      - "./docker/data/logs/nginx/error.log:/var/logs/nginx/error.log"
      - "./docker/etc/ssl:/etc/ssl"
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    networks:
      localca:
        ipv4_address: ${SUBNET}.4
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: docker-phpmyadmin
    ports:
      - "${PHP_MYADMIN}:80"
    volumes:
      -   ./docker/etc/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      -   ./docker/etc/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
    networks:
      localca:
        ipv4_address: ${SUBNET}.5
    restart: always
    depends_on:
      - mysql
networks:
  localca:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}.0/28